name: rental_app
description: A cross-platform rental application in Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
